//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotBox.BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotBox.BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;&lt;!-- written by IQ422 Iss3.10 Nov 13 2012 Saved 2016-11-4T18:40:29TZD --&gt;&lt;TrendProject&gt;&lt;Site CncAddress=&quot;71&quot; TuaString=&quot;T/IQ3 - 00:10:70:0B:47:A9/TCP,,,192.168.0.101,10071///11/1/&quot;&gt;&lt;Lan IsLocal=&quot;True&quot; LanNumber=&quot;11&quot;&gt;&lt;Device DeviceNumber=&quot;1&quot; VersionString=&quot;IQ422 Iss3.10 Nov 13 2012&quot;&gt;&lt;DeviceOverview DeviceType=&quot;q&quot; MajorVersion=&quot;3&quot; MinorVersion=&quot;1&quot; HexEncoded=&quot;711B1B1B41333130&quot; Revision=&quot;0&quot;&gt;&lt;/DeviceOverview&gt;&lt;Module Name=&quot;S100&quot; SubTypeNumber=&quot;-1&quot;&gt;&lt;Param Nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLString {
            get {
                return ResourceManager.GetString("XMLString", resourceCulture);
            }
        }
    }
}
