//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotBox.DAL.HotboxDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HOTBOXDBEntities : DbContext
    {
        public HOTBOXDBEntities()
            : base("name=HOTBOXDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblOutstation> tblOutstations { get; set; }
        public virtual DbSet<tblPointValue> tblPointValues { get; set; }
        public virtual DbSet<tblStrategy> tblStrategies { get; set; }
    }
}
