//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotBox.DAL.HotboxDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOutstation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOutstation()
        {
            this.tblStrategies = new HashSet<tblStrategy>();
        }
    
        public byte OutstationId { get; set; }
        public string OutstationHostname { get; set; }
        public bool OutstationLearned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStrategy> tblStrategies { get; set; }
    }
}
