//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotBox.DAL.HotboxDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStrategy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStrategy()
        {
            this.tblPointValues = new HashSet<tblPointValue>();
        }
    
        public int theIndex { get; set; }
        public byte OutstationNo { get; set; }
        public string Point { get; set; }
        public string theLabel { get; set; }
        public string theUnit { get; set; }
    
        public virtual tblOutstation tblOutstation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPointValue> tblPointValues { get; set; }
    }
}
